/* WeatherGPT — key-free, real weather and radar intelligence. */
const places={India:{'Tamil Nadu':['Chennai','Coimbatore','Madurai'],Maharashtra:['Mumbai','Pune','Nagpur'],Karnataka:['Bengaluru','Mysuru','Mangaluru'],'Delhi NCR':['New Delhi','Gurugram','Noida'],West_Bengal:['Kolkata','Darjeeling','Siliguri']},'United States':{California:['San Francisco','Los Angeles','San Diego'],New_York:['New York','Buffalo']},'United Kingdom':{England:['London','Manchester','Birmingham']},Australia:{Victoria:['Melbourne','Geelong'],NSW:['Sydney','Newcastle']}};
const coords={Chennai:[13.0827,80.2707],Mumbai:[19.076,72.8777],Delhi:[28.6139,77.209],Kolkata:[22.5726,88.3639],Bengaluru:[12.9716,77.5946],Coimbatore:[11.0168,76.9558],Madurai:[9.9252,78.1198],Pune:[18.5204,73.8567],Nagpur:[21.1458,79.0882],Mysuru:[12.2958,76.6394],Mangaluru:[12.9141,74.856],'New Delhi':[28.6139,77.209],Gurugram:[28.4595,77.0266],Noida:[28.5355,77.391],Darjeeling:[27.036,88.2627],Siliguri:[26.7271,88.3953],London:[51.5072,-.1276],Manchester:[53.4808,-2.2426],Birmingham:[52.4862,-1.8904],Sydney:[-33.8688,151.2093],Melbourne:[-37.8136,144.3617],'San Francisco':[37.7749,-122.4194],'Los Angeles':[34.0522,-118.2437],'San Diego':[32.7157,-117.1611],'New York':[40.7128,-74.006],Buffalo:[42.8864,-78.8784],Geelong:[-38.1499,144.3617],Newcastle:[-32.9283,151.7817]};
const fallback={temperature_2m:31,relative_humidity_2m:71,apparent_temperature:36,precipitation:0,weather_code:2,wind_speed_10m:16}, weatherKeys='temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m';
let state={city:'Chennai',lat:13.0827,lon:80.2707,data:fallback,daily:null,selected:new Date(),isLive:true};let map,marker,street,satellite,radarLayer,hazards,windLayer,frames=[],frame=0,playTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pad=n=>String(n).padStart(2,'0'),dateKey=d=>d.toISOString().slice(0,10);
const icon=c=>c===0?'☀️':c<=2?'🌤️':c<=48?'☁️':c<=67?'🌦️':c<=77?'❄️':'⛈️',description=c=>c===0?'Clear sky':c<=2?'Mostly clear':c<=48?'Cloudy':c<=67?'Rain showers':c<=77?'Snow showers':'Thunderstorms';
function populate(){let p=places[$('#country').value];$('#state').innerHTML=Object.keys(p).map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('');populateDistrict()}function populateDistrict(){let a=places[$('#country').value]?.[$('#state').value]||[];$('#district').innerHTML=a.map(x=>`<option>${x}</option>`).join('')}
function active(selector,value){$$(selector).forEach(x=>x.classList.toggle('active',x.dataset.mode===value||x.dataset.overlay===value))}
function initMap(){map=L.map('map',{zoomControl:false}).setView([state.lat,state.lon],7);L.control.zoom({position:'bottomright'}).addTo(map);street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});marker=L.marker([state.lat,state.lon]).addTo(map);hazards=L.layerGroup();windLayer=L.layerGroup();map.on('click',e=>{Object.assign(state,{city:'Pinned map point',lat:e.latlng.lat,lon:e.latlng.lng,isLive:true});setTime(new Date());getWeather(true)})}
function risk(){let d=state.data,p=state.daily?.precipitation_probability_max?.[0]||0;return {heat:d.apparent_temperature>=40||d.temperature_2m>=36,flood:d.weather_code>=80||d.precipitation>=8||p>=75,wind:d.wind_speed_10m>=30,rain:d.weather_code>=51||p>=45}}
function drawHazards(kind='all'){hazards.clearLayers();windLayer.clearLayers();let r=risk(),d=state.data,c=[state.lat,state.lon],add=(colour,title,sub,radius=30000)=>L.circle(c,{radius,color:colour,fillColor:colour,fillOpacity:.22,weight:2}).bindTooltip(`<b>${title}</b><br>${sub}`,{permanent:true,direction:'top',className:'hazard-label'}).addTo(hazards);if((kind==='all'||kind==='heat')&&r.heat)add('#e8513f','HEAT STRESS',`Feels ${Math.round(d.apparent_temperature)}°C`);if((kind==='all'||kind==='flood')&&r.flood)add('#2274c9','FLOOD WATCH','Heavy-rain signal detected',40000);if((kind==='all'||kind==='wind')&&r.wind)L.circle(c,{radius:26000,color:'#7c4dff',fillColor:'#7c4dff',fillOpacity:.18}).bindTooltip(`<b>WIND ADVISORY</b><br>${Math.round(d.wind_speed_10m)} km/h`,{permanent:true,direction:'bottom',className:'hazard-label'}).addTo(windLayer);if(!r.heat&&!r.flood&&!r.wind&&kind==='all')add('#16a86b','LOW CURRENT RISK','No high-impact local signal',18000);if(kind!=='wind')hazards.addTo(map);if(kind==='wind'||r.wind)windLayer.addTo(map)}
function clearOverlays(){[radarLayer,hazards,windLayer].forEach(x=>x&&map.hasLayer(x)&&map.removeLayer(x))}function selectOverlay(type){$('#map').dataset.overlay=type;active('.layer-chip',type);clearOverlays();if(type==='radar'){radarLayer?radarLayer.addTo(map):loadRadar()}else drawHazards(type);$('#mapStatus').textContent=type==='radar'?'Live precipitation radar':type==='heat'?'Heat stress risk layer':type==='flood'?'Flood watch risk layer':'Wind advisory layer'}
function selectMode(mode){active('.map-tools button',mode);if(mode==='satellite'){map.removeLayer(street);satellite.addTo(map);selectOverlay('radar')}else{map.removeLayer(satellite);street.addTo(map);mode==='hazards'?(selectOverlay('heat'),drawHazards('all')):selectOverlay('radar')}}
async function loadRadar(){try{let r=await fetch('https://api.rainviewer.com/public/weather-maps.json');if(!r.ok)throw 0;let x=await r.json();frames=[...(x.radar?.past||[]),...(x.radar?.nowcast||[])];if(!frames.length)throw 0;frame=frames.length-1;$('#radarTimeline').max=frame;showRadar(frame)}catch{$('#timelineTitle').textContent='Radar unavailable · point weather still works'}}function showRadar(index){if(!frames.length)return;frame=Math.max(0,Math.min(frames.length-1,+index));$('#radarTimeline').value=frame;if(radarLayer)map.removeLayer(radarLayer);let f=frames[frame];radarLayer=L.tileLayer(`https://tilecache.rainviewer.com${f.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.72,zIndex:4,attribution:'Radar © RainViewer'});if($('#map').dataset.overlay==='radar'||!$('#map').dataset.overlay)radarLayer.addTo(map);let t=new Date(f.time*1000);$('#timelineTitle').textContent=`Live radar playback · ${t.toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}`;$('#mapStatus').textContent=`Radar frame · ${t.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}
function setTime(d){$('#mapYear').value=d.getFullYear();$('#mapMonth').value=d.getMonth()+1;days();$('#mapDay').value=d.getDate();$('#mapHour').value=d.getHours();$('#mapMinute').value=Math.floor(d.getMinutes()/15)*15}function days(){let n=new Date(+$('#mapYear').value,+$('#mapMonth').value,0).getDate(),old=+$('#mapDay').value||1;$('#mapDay').innerHTML=Array.from({length:n},(_,i)=>`<option value="${i+1}">${pad(i+1)}</option>`).join('');$('#mapDay').value=Math.min(old,n)}function readTime(){return new Date(+$('#mapYear').value,+$('#mapMonth').value-1,+$('#mapDay').value,+$('#mapHour').value,+$('#mapMinute').value)}
async function getWeather(live=false){let chosen=live?new Date():state.selected;state.isLive=live;state.selected=chosen;let today=new Date(),ahead=(chosen-today)/864e5,date=dateKey(chosen);$('#updated').textContent=live?'Fetching live weather…':'Loading selected time…';try{let url=live||ahead>-2&&ahead<16?`https://api.open-meteo.com/v1/forecast?latitude=${state.lat}&longitude=${state.lon}&current=${weatherKeys}&hourly=${weatherKeys}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&past_days=30`:`https://archive-api.open-meteo.com/v1/archive?latitude=${state.lat}&longitude=${state.lon}&start_date=${date}&end_date=${date}&hourly=${weatherKeys}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`;let res=await fetch(url);if(!res.ok)throw 0;let x=await res.json();state.daily=x.daily;if(live&&x.current)state.data=x.current;else{let target=`${date}T${pad(chosen.getHours())}:00`,i=Math.max(0,(x.hourly?.time||[]).findIndex(v=>v===target));state.data=Object.fromEntries(weatherKeys.split(',').map(k=>[k,x.hourly?.[k]?.[i]??fallback[k]]))}let stamp=live?'Live · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):`${chosen.toLocaleDateString([],{year:'numeric',month:'short',day:'numeric'})} · ${pad(chosen.getHours())}:${pad(chosen.getMinutes())} (hourly model)`;$('#updated').textContent=stamp;if(!live)$('#timelineTitle').textContent=`Selected point weather · ${stamp}`;render()}catch{state.data=fallback;state.daily=null;$('#updated').textContent='Demo data shown · connection unavailable';render()}}
function render(){let d=state.data;$('#cityName').textContent=state.city;$('#chatLocation').textContent=state.city;$('#placeLabel').textContent=`${state.city.toUpperCase()} · ${state.lat.toFixed(2)}°, ${state.lon.toFixed(2)}°`;$('#temp').textContent=Math.round(d.temperature_2m)+'°';$('#condition').textContent=description(d.weather_code);$('#feels').textContent='Feels like '+Math.round(d.apparent_temperature)+'°';$('#weatherIcon').textContent=icon(d.weather_code);$('#humidity').textContent=Math.round(d.relative_humidity_2m)+'%';$('#wind').textContent=Math.round(d.wind_speed_10m)+' km/h';$('#rain').textContent=(d.precipitation||0)+' mm';marker.setLatLng([state.lat,state.lon]).bindPopup(`<b>${state.city}</b><br>${Math.round(d.temperature_2m)}°C · ${description(d.weather_code)}`);map.setView([state.lat,state.lon],Math.max(map.getZoom(),7));$('#mapCoordinates').textContent=`${state.lat.toFixed(2)}°, ${state.lon.toFixed(2)}°`;forecast();alerts();advice();chart();if($('#map').dataset.overlay&&$('#map').dataset.overlay!=='radar')selectOverlay($('#map').dataset.overlay)}
function forecast(){let a=state.daily?.time?.slice(0,5)||Array.from({length:5},(_,i)=>[new Date(Date.now()+i*864e5).toISOString().slice(0,10)]),d=state.daily;$('#forecastDays').innerHTML=a.map((x,i)=>{let c=d?.weather_code?.[i]??[2,3,61,61,2][i],hi=d?.temperature_2m_max?.[i]??31,lo=d?.temperature_2m_min?.[i]??25,p=d?.precipitation_probability_max?.[i]??16;return `<div class="day"><span>${i?' '+new Date(x).toLocaleDateString('en',{weekday:'short'}):'Today'}</span><i>${icon(c)}</i><b>${Math.round(hi)}° <small>${Math.round(lo)}°</small></b><small>☂ ${p}%</small></div>`}).join('');$('#explanation').textContent=(d?.precipitation_probability_max?.slice(0,3).some(x=>x>50))?'Rain probability rises as moisture and cloud cover increase. Keep outdoor plans flexible.':'Stable conditions are expected, with no significant precipitation signal in the next 72 hours.'}
function alerts(){let d=state.data,p=state.daily?.precipitation_probability_max?.[0]||0,a=[];if(d.weather_code>=80||p>=75||d.precipitation>=8)a.push(['🌊','Flood / heavy-rain watch','Avoid low-lying roads, water crossings, and fast-moving water.','HIGH']);if(d.temperature_2m>=35||d.apparent_temperature>=39)a.push(['☀️','Heat-stroke advisory','Hydrate, seek shade, and avoid strenuous activity during peak heat.','MODERATE']);if(d.wind_speed_10m>=35)a.push(['💨','Strong wind advisory','Secure loose objects and avoid trees, coastlines, and exposed routes.','MODERATE']);if(!a.length)a.push(['✓','No severe weather alert','Current conditions do not show a high-impact local signal.','LOW RISK']);$('#alertCount').textContent=a.length;$('#alertList').innerHTML=a.map(x=>`<div class="alert-item"><i>${x[0]}</i><div><b>${x[1]}</b><p>${x[2]}</p><span class="tag">${x[3]}</span></div></div>`).join('')}
const tips={farmer:['Farm-smart plan for today','Check irrigation before the afternoon heat builds.','Schedule spraying only in a dry, low-wind window.','Keep harvested produce covered and drainage paths clear.'],marine:['Marine safety briefing','Check the latest official marine bulletin before departure.','Carry communication and flotation safety equipment.','Return early if winds build or visibility drops.'],citizen:['Your local safety plan','Carry water and plan shade breaks during warm hours.','Check local traffic and flood-prone routes before travel.','Enable official emergency alerts on your phone.'],aviation:['Aviation weather snapshot','Review terminal forecasts and NOTAMs before dispatch.','Monitor wind and visibility changes close to departure.','Keep alternate routing ready for convective conditions.']};function advice(){let a=tips[$('#sector').value];$('#advisoryContent').innerHTML=`<h3 class="advice-title">${a[0]}</h3><p class="advice-intro">Practical actions aligned to the conditions at your selected point.</p><ul class="actions">${a.slice(1).map(x=>`<li>${x}</li>`).join('')}</ul>`}function chart(){let a=state.daily?.temperature_2m_max?.slice(0,31)||Array.from({length:31},(_,i)=>29+Math.sin(i*.52)*2),min=Math.min(...a)-1,max=Math.max(...a)+1,w=520,h=150,p=a.map((v,i)=>`${i/(a.length-1)*w},${h-16-(v-min)/(max-min)*(h-35)}`).join(' ');$('#climateChart').innerHTML=`<polyline points="${p}" fill="none" stroke="#18a972" stroke-width="3" stroke-linecap="round"/>`;$('#avgTemp').textContent=(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1)+'°C'}
function update(city){let p=coords[city];if(p){Object.assign(state,{city,lat:p[0],lon:p[1],isLive:true});setTime(new Date());getWeather(true)}}
$('#country').onchange=populate;$('#state').onchange=populateDistrict;$('#update').onclick=()=>update($('#district').value);$$('[data-place]').forEach(b=>b.onclick=()=>update(b.dataset.place));$('#sector').onchange=advice;$('#alertRefresh').onclick=()=>getWeather(state.isLive);$('#locate').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{Object.assign(state,{city:'Your location',lat:p.coords.latitude,lon:p.coords.longitude});setTime(new Date());getWeather(true)},()=>alert('Location permission was unavailable. Select a place or click the map instead.'));$('#timelineLive').onclick=()=>{setTime(new Date());getWeather(true);selectOverlay('radar');loadRadar()};$('#applyMapTime').onclick=()=>{state.selected=readTime();getWeather(false);selectOverlay('heat')};$('#mapMonth').onchange=days;$('#mapYear').onchange=days;$('#radarTimeline').oninput=e=>showRadar(e.target.value);$('#radarBack').onclick=()=>showRadar(frame-1);$('#radarForward').onclick=()=>showRadar(frame+1);$('#radarPlay').onclick=()=>{if(playTimer){clearInterval(playTimer);playTimer=null;$('#radarPlay').textContent='▶'}else{$('#radarPlay').textContent='❚❚';playTimer=setInterval(()=>showRadar((frame+1)%frames.length),650)}};$$('.map-tools button').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));$$('.layer-chip').forEach(b=>b.onclick=()=>selectOverlay(b.dataset.overlay));

const panel=$('#assistantPanel');
function message(t,who){let x=document.createElement('div');x.className=who+'-message';x.textContent=t;$('#chat').append(x);$('#chat').scrollTop=9999}

// --- NEW GEMINI AI REPLY FUNCTION ---
async function reply(q) {
  let d = state.data;
  let context = `At ${state.city}: ${Math.round(d.temperature_2m)}°C, ${description(d.weather_code).toLowerCase()}, humidity ${Math.round(d.relative_humidity_2m)}%, wind ${Math.round(d.wind_speed_10m)} km/h.`;
  let prompt = `You are WeatherGPT, a helpful weather and safety AI. Keep answers concise. Current weather context: ${context}. User asks: ${q}`;
  let key = 'AQ.Ab8RN6J0oEOYCHnFGkC6CELnTt2FrKQbJeuvGX5GJmgIQ8yMZQ';
  
  try {
    let res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
    });
    let data = await res.json();
    let ans = data.candidates?.[0]?.content?.parts?.[0]?.text || "I'm having trouble processing that right now.";
    message(ans, 'bot');
  } catch (e) {
    console.error(e);
    message("I'm having trouble connecting to the AI.", 'bot');
  }
}
// -------------------------------------

$('#assistantLaunch').onclick=()=>panel.classList.toggle('open');
$('#closeAssistant').onclick=()=>panel.classList.remove('open');
$('#chatForm').onsubmit=e=>{e.preventDefault();let q=$('#chatInput').value.trim();if(q){message(q,'user');$('#chatInput').value='';reply(q)}}; $$('.suggestions button').forEach(b=>b.onclick=()=>{message(b.textContent,'user');reply(b.textContent)});$('#climateQuestion').onclick=()=>{panel.classList.add('open');message(`What climate trend would you like to understand for ${state.city}?`,'bot')};
$('#voice').onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Voice input is not supported in this browser.');let r=new R();r.lang=$('#language').value==='hi'?'hi-IN':'en-IN';r.onresult=e=>{$('#chatInput').value=e.results[0][0].transcript;$('#chatForm').requestSubmit()};r.start()};
$('#language').onchange=e=>{if(e.target.value!=='en')alert('The live data and map controls remain available in English; full language translation can be added next.')};
function initTime(){let n=new Date();$('#mapMonth').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2020,i).toLocaleString('en',{month:'short'})}</option>`).join('');$('#mapHour').innerHTML=Array.from({length:24},(_,i)=>`<option value="${i}">${pad(i)}</option>`).join('');setTime(n)}populate();initTime();initMap();selectOverlay('radar');loadRadar();getWeather(true);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();panel.classList.add('open');$('#chatInput').focus()}});
